---
name: Lint
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  super-linter:
    name: Lint
    permissions:
      contents: read
      packages: read # Required for package listing
      pull-requests: write # To allow PR comments from tools that use the GITHUB_TOKEN
      statuses: write # To report GitHub Actions status checks
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Update README example pins
        uses: suzuki-shunsuke/pinact-action@cf51507d80d4d6522a07348e3d58790290eaf0b6 # v2.0.0
        with:
          update: "true"
          verify: "true"
          min_age: "7"

      - uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
        with:
          advanced-security: false
          persona: pedantic

  are-we-good:
    name: Rollup
    runs-on: ubuntu-latest
    needs: [super-linter]
    if: always()
    steps:
      - uses: lowlydba/are-we-good@7efad05442f92a1203940ca8b79dd4fb930e75d4 # v1.0.2
        with:
          jobs: ${{ toJSON(needs) }}
