---
name: Lint
on:
  pull_request:

permissions:
  contents: read
  packages: read
  pull-requests: write # To allow PR comments from tools that use the GITHUB_TOKEN
  statuses: write # To report GitHub Actions status checks

jobs:
  super-linter:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: super-linter/super-linter/slim@61abc07d755095a68f4987d1c2c3d1d64408f1f9 #v8.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false