---
name: Lint
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  super-linter:
    name: Lint
    permissions:
      contents: read
      packages: read # Required for package listing
      pull-requests: write # To allow PR comments from tools that use the GITHUB_TOKEN
      statuses: write # To report GitHub Actions status checks
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Check action pins
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          verify: "true"
          min_age: "7"

      - uses: zizmorcore/zizmor-action@b1d7e1fb5de872772f31590499237e7cce841e8e # v0.5.3
        with:
          advanced-security: false
          persona: pedantic

  are-we-good:
    name: Rollup
    runs-on: ubuntu-latest
    needs: [super-linter]
    if: always()
    steps:
      - uses: lowlydba/are-we-good@7efad05442f92a1203940ca8b79dd4fb930e75d4 # v1.0.2
        with:
          jobs: ${{ toJSON(needs) }}
