---
name: Test action

on:
  push:
  pull_request:

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x, 18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Run action
        uses: ./
        with:
          audit: 'false'
          fund: 'false'
          progress: 'false'
          update-notifier: 'false'
          prefer-offline: 'true'
          loglevel: 'error'

      - name: Assert npm config settings
        shell: bash
        run: |
          expected_audit="false"
          expected_fund="false"
          expected_progress="false"
          expected_update_notifier="false"
          expected_prefer_offline="true"
          expected_loglevel="error"

          # Retrieve current npm config values
          actual_audit=$(npm config get audit)
          actual_fund=$(npm config get fund)
          actual_progress=$(npm config get progress)
          actual_update_notifier=$(npm config get update-notifier)
          actual_prefer_offline=$(npm config get prefer-offline)
          actual_loglevel=$(npm config get loglevel)

          echo "Validating npm configurations:"
          echo "audit: expected $expected_audit, got $actual_audit"
          echo "fund: expected $expected_fund, got $actual_fund"
          echo "progress: expected $expected_progress, got $actual_progress"
          echo "update-notifier: expected $expected_update_notifier, got $actual_update_notifier"
          echo "prefer-offline: expected $expected_prefer_offline, got $actual_prefer_offline"
          echo "loglevel: expected $expected_loglevel, got $actual_loglevel"

          # Compare actual vs expected values
          if [ "$actual_audit" != "$expected_audit" ]; then echo "Mismatch in audit"; exit 1; fi
          if [ "$actual_fund" != "$expected_fund" ]; then echo "Mismatch in fund"; exit 1; fi
          if [ "$actual_progress" != "$expected_progress" ]; then echo "Mismatch in progress"; exit 1; fi
          if [ "$actual_update_notifier" != "$expected_update_notifier" ]; then echo "Mismatch in update-notifier"; exit 1; fi
          if [ "$actual_prefer_offline" != "$expected_prefer_offline" ]; then echo "Mismatch in prefer_offline"; exit 1; fi
          if [ "$actual_loglevel" != "$expected_loglevel" ]; then echo "Mismatch in loglevel"; exit 1; fi

          echo "All npm configurations match the expected values."
